# Generated by Django 5.2.1 on 2025-08-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istak_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='last_borrowed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='qr_code',
        ),
    ]
