# Generated by Django 5.2.1 on 2025-08-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istak_backend', '0002_remove_customuser_qr_code_remove_item_last_borrowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_borrowed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
