# Generated by Django 5.2.1 on 2025-08-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istak_backend', '0003_item_last_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
