# Generated by Django 5.2.5 on 2025-09-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istak_backend', '0004_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
