# Generated by Django 5.2.5 on 2025-09-15 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istak_backend', '0005_customuser_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='borrowtransaction',
            name='borrowerName',
        ),
        migrations.RemoveField(
            model_name='borrowtransaction',
            name='schoolId',
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrow_transactions', to='istak_backend.borrower'),
        ),
    ]
