# Generated by Django 5.2.5 on 2025-09-15 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istak_backend', '0006_borrower_remove_borrowtransaction_borrowername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='borrow_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to='istak_backend.borrowtransaction'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='is_active',
            field=models.BooleanField(blank=True, default=None, help_text='Set to True if active, False if inactive, or None if pending.', null=True, verbose_name='active status'),
        ),
    ]
