# Generated by Django 5.2.5 on 2025-09-21 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istak_backend', '0007_borrower_borrow_transaction_borrower_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowtransaction',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='borrowtransaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='borrowtransaction',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='borrowtransaction',
            name='mobile_user',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='borrow_transaction',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='is_active',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('item_name', 'manager')},
        ),
        migrations.RemoveField(
            model_name='registrationrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='borrower',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='school_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fcm_token',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue')], db_index=True, default='borrowed', max_length=20)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='istak_backend.borrower')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='istak_backend.item')),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'user_web'}, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_managed', to=settings.AUTH_USER_MODEL)),
                ('mobile_user', models.ForeignKey(limit_choices_to={'role': 'user_mobile'}, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='current_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_current', to='istak_backend.transaction'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='last_borrowed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'manager'], name='istak_backe_status_bd5b15_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'borrowed')), fields=('item',), name='unique_active_borrow_per_item'),
        ),
        migrations.DeleteModel(
            name='BorrowTransaction',
        ),
    ]
